### ISSUE TITLE
duplicated remove method in trans_exp

### ISSUE THREAD

**Issue by hjames1** [xjsun1221/tinyarray#1]
hello!
I have noticed that the duplicated remove method in function trans_exp is:
```
mRNA_exp = mRNA_exp[!duplicated(x$gene_name),]
x = x[!duplicated(x$gene_name),]
rownames(mRNA_exp) = x$gene_name
```
It doesn't take into account the counts of gene expression. Maybe the appropriate approach is to preserve the genes with the highest expression levels.

**Comment by xjsun1221** [comment]
ok!thanks for your suggestion, i will modify it as soon as possible

**Comment by xjsun1221** [comment]
> hello!
> I have noticed that the duplicated remove method in function trans_exp is:
> 
> ```
> mRNA_exp = mRNA_exp[!duplicated(x$gene_name),]
> x = x[!duplicated(x$gene_name),]
> rownames(mRNA_exp) = x$gene_name
> ```
> 
> It doesn't take into account the counts of gene expression. Maybe the appropriate approach is to preserve the genes with the highest expression levels.

done

**Comment by hjames1** [comment]
one error occured in `rowsum`
Error in rowsum.data.frame(mRNA_exp) : 
  argument "group" is missing, with no default

maybe it should be changed into `rowSums`.

**Comment by xjsun1221** [comment]
> one error occured in `rowsum`
> Error in rowsum.data.frame(mRNA_exp) :
> argument "group" is missing, with no default
> 
> maybe it should be changed into `rowSums`.

ok

**Comment by hjames1** [comment]
The script of sorting is wrong,two more lines should be added.
`if(order) mRNA_exp = mRNA_exp[order(rowSums(mRNA_exp),decreasing = T),]`
`m <- match(rownames(mRNA_exp),x$gene_id)`
`x <- x[m,]`

**Comment by xjsun1221** [comment]
I thought about it later. The code to modify the order should not be added. I will delete this parameter because the id conversion should not be affected by the amount of expression, so that if multiple data are analyzed together, there will be different genes. So I choose a unified way to directly remove duplicate values, if you want to use it, you can handle it yourself.
