### ISSUE TITLE
报错Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):  there is no package called ‘clusterProfiler’

### ISSUE THREAD

**Issue by kaifenghuang07** [xjsun1221/tinyarray#10]
Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘clusterProfiler’

**Comment by kaifenghuang07** [comment]
Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘org.Hs.eg.db’

**Comment by kaifenghuang07** [comment]
把这几个包全下载了就可以用了 ：》

**Comment by 8257ok** [comment]
请问这个问题，你解决了没？我把缺的包下载了，还是出错
