### ISSUE TITLE
希望为PCA分析提供显示样本编号选项，对于少数离群样本方便识别

### ISSUE THREAD

**Issue by ydx1013** [xjsun1221/tinyarray#11]
factoextra::fviz_pca_ind(dat.pca, 
                             geom.ind = c("point", "text"),  # 显示点和样本号
                             col.ind = group_list, 
                             addEllipses = addEllipses, 
                             palette = col, 
                             legend.title = "Groups", 
                             title = title, 
                             ...)

**Comment by xjsun1221** [comment]
所有fviz_pca_ind的参数都可以用的，只是无法自动补齐
