### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Kevinhokahey** [xjsun1221/tinyarray#2]
孙老师您好，我目前电脑用的是MAC，但您这个tinyarray包貌似是Windows系统的包，所以我下载后安装的时候R报错了。说安装不了“Error in install.packages : cannot install Windows binary packages on this platform”
请问后续该如何解决呢？非常感谢

**Comment by xjsun1221** [comment]
你代码写错了。但是没有截图 所以我也不知道你代码错在哪，安装方式在readme有介绍了
