### ISSUE TITLE
Error in if (any(exp < 0)) { : 需要TRUE/FALSE值的地方不可以用缺少值

### ISSUE THREAD

**Issue by ayueme** [xjsun1221/tinyarray#4]
孙老师您好：
使用geo_download(x,by_annopbrobe = T)下载报错：
Error in if (any(exp < 0)) { : 需要TRUE/FALSE值的地方不可以用缺少值。
但是直接使用geoChina下载不会报错，使用的数据集是gse52219。

**Comment by xjsun1221** [comment]
那是因为这个数据里面有NA 我写函数的时候没考虑这种问题数据 后面更新一下

**Comment by xjsun1221** [comment]
我已经更新好啦。

**Comment by ayueme** [comment]
感恩！
