### ISSUE TITLE
surv_KM和surv_cox表达矩阵问题

### ISSUE THREAD

**Issue by quaresma00** [xjsun1221/tinyarray#5]
1. 以上两个函数的表达矩阵是传入count，tpm，还是log2后的矩阵，还是说函数内部已经进行log2化或z-score处理
2. 假设surv_KM后获得一组基因，想将这组基因传入lasso，那传入lasso的表达矩阵有什么要求，因为之前经过surv_KM，应该surv_KM内部运算的和lasso运算的表达矩阵最好一样（比如都是log2(Count)这样？）

**Comment by xjsun1221** [comment]
> 1. 以上两个函数的表达矩阵是传入count，tpm，还是log2后的矩阵，还是说函数内部已经进行log2化或z-score处理
> 2. 假设surv_KM后获得一组基因，想将这组基因传入lasso，那传入lasso的表达矩阵有什么要求，因为之前经过surv_KM，应该surv_KM内部运算的和lasso运算的表达矩阵最好一样（比如都是log2(Count)这样？）

做生存分析和建模的数据都要logCPM或者logTPM，前后一致就行啦。函数内部不做任何处理。

就是把surv_KM选出的基因从表达矩阵里面取子集取出来，转置，作为lasso回归的x参数
