### ISSUE TITLE
library(tinyarray) Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):  载入了名字空间‘tidyr’ 1.2.1，但需要的是>= 1.3.0 In addition: Warning message: 程辑包‘tinyarray’是用R版本4.2.2 来建造的 

### ISSUE THREAD

**Issue by Dabaixian** [xjsun1221/tinyarray#8]
library(tinyarray)
Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 载入了名字空间‘tidyr’ 1.2.1，但需要的是>= 1.3.0
In addition: Warning message:
程辑包‘tinyarray’是用R版本4.2.2 来建造的 

您好， 
    请问在使用过程中遇到了这个问题，且重新安装后也依旧报错，请问这该怎么办呢？

**Comment by xjsun1221** [comment]
更新一下你的tidyr包哦


| |
孙小洁
|
|
***@***.***
|
签名由网易邮箱大师定制
在2023年2月17日 ***@***.***> 写道：

library(tinyarray)
Error: package or namespace load failed for ‘tinyarray’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
载入了名字空间‘tidyr’ 1.2.1，但需要的是>= 1.3.0
In addition: Warning message:
程辑包‘tinyarray’是用R版本4.2.2 来建造的

您好，
请问在使用过程中遇到了这个问题，且重新安装后也依旧报错，请问这该怎么办呢？
